services:
  bot:
    image: mikkelnilsson/ano-py-bot:runtime
    build: ../bot
    command: bash -c "alembic upgrade head && python bot.py"
    restart: unless-stopped
    environment:
      - PYBOTTOKEN=${PYBOTTOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - IS_PROD=${IS_PROD}
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
      - LAVALINK_PORT=${LAVALINK_PORT}
    depends_on:
      - lavalink
      - db
    networks:
      - lavalink
    volumes:
      - ${LOG_MOUNT_LOCATION}:/app/logs

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4 # pin the image version to Lavalink v4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=${LAVALINK_PORT} # set lavalink server port
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD} # set password for lavalink
    ports:
      - ${LAVALINK_PORT}:${LAVALINK_PORT}
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
    networks:
      - lavalink

  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 6543:${POSTGRES_PORT}
    volumes:
      - ${POSTGRES_DATA_MOUNT_LOCATION}:/var/lib/postgresql/data
    networks:
      - lavalink

networks:
  lavalink:
    # create a lavalink network you can add other containers to, to give them access to Lavalink
    name: lavalink
