discord:
    replay-messages: true
logging:
    level: 'info'
bot:
    prefix: '!'
    owners: [
        215044487871725573
    ]
connection-string: 'postgresql+psycopg2://{user}:{password}@0.0.0.0:{port}/{database}'
