---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - master
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AnoPyBot
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Bot
        uses: docker/build-push-action@v2
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ano-py-bot:runtime
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ano-py-bot:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ano-py-bot:webbuildcache,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/bot.key
          chmod 600 ~/.ssh/bot.key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Copy remote_files directory to server
        run: |
          scp -i ~/.ssh/bot.key -o StrictHostKeyChecking=no -r remote_files/ $SSH_USER@$SSH_HOST:/AnoPyBot/

      - name: Create .env file
        run: >  
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/bot.key -o StrictHostKeyChecking=no
          "echo -e \"IS_PROD=$IS_PROD\\nPOSTGRES_USER=$POSTGRES_USER\\nPOSTGRES_PASSWORD=$POSTGRES_PASSWORD\\nPOSTGRES_DB=$POSTGRES_DB\\nPOSTGRES_PORT=$POSTGRES_PORT\\nPYBOTTOKEN=$PYBOTTOKEN\\nPOSTGRES_DATA_MOUNT_LOCATION=$POSTGRES_DATA_MOUNT_LOCATION\\nLOG_MOUNT_LOCATION=$LOG_MOUNT_LOCATION\\nLAVALINK_PORT=$LAVALINK_PORT\\nLAVALINK_PASSWORD=$LAVALINK_PASSWORD\" > /AnoPyBot/remote_files/.env"
        env:
          IS_PROD: ${{ vars.IS_PROD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          PYBOTTOKEN: ${{ secrets.PYBOTTOKEN }}
          POSTGRES_DATA_MOUNT_LOCATION: ${{ secrets.POSTGRES_DATA_MOUNT_LOCATION }}
          LOG_MOUNT_LOCATION: ${{ secrets.LOG_MOUNT_LOCATION }}
          LAVALINK_PORT: ${{ secrets.LAVALINK_PORT }}
          LAVALINK_PASSWORD: ${{ secrets.LAVALINK_PASSWORD }}

      - name: Deploy to server
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/bot.key -o StrictHostKeyChecking=no
          "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
          cp -r /AnoPyBot/remote_files/* /AnoPyBot/ && cd /AnoPyBot/ && /AnoPyBot/deploy.sh"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
